### ISSUE TITLE
Exception thrown when publishing an event using DaprClient from Java SDK of Dapr 

### ISSUE THREAD

**Issue by pagufler** [dapr/java-sdk#257]
## In what area(s)?
I am using io.dapr.client.DaprClient -> publishEvent(String var1, Object var2):

```
com.fasterxml.jackson.databind.ObjectMapper om = ObjectMapper();
...
try {
            publisher.publishEvent(
                    "core.adapters.delete",
                    om.writeValueAsBytes(bc)).doOnError(
                        throwable -> LOG.error(throwable.getMessage(), throwable))
                        .subscribe(
                                value -> LOG.trace("Subscribed to published event: {}", value),
                                err -> LOG.error(err.getMessage(), err),
                                () -> LOG.trace("Publishing completed")
                        );
        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }
```

I tried the code yesterday with a topic that already exists. Yesterday it was successful. Tried it today with a new topic, then the exception occurred. Then tried again the old topic, also in this case the exception occurs.
There comes no exception at startup. When I call the above code to publish an event, the exception occurrs.

> /area runtime
Windows
Java JDK 12.0.2
No company proxy involved. 
On local machine

## What version of Dapr?
dapr java sdk 0.3.0

## Expected Behavior
Events can be published without exception

## Actual Behavior
When an event is published, I get following exception:
2020/03/25T16:03:55.697 core [http-nio-8081-exec-2] ERROR c.b.r.s.r.a.s.BundlesServiceImplementation.lambda$publishAdapterEvent$3(486) - io.grpc.StatusRuntimeException: UNAVAILABLE: io exception [161818, , Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36]
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at io.dapr.client.DaprClientGrpc.lambda$publishEvent$0(DaprClientGrpc.java:91)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4193)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4059)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3995)
	at com.bosch.riot.server.ServiceImpl.publishAdapterEvent(ServiceImpl.java:487)
	at com.bosch.riot.server.Controller$$FastClassBySpringCGLIB$$de67ea92.invoke(<generated>)
    ...
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 common frames omitted
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:50051
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)

## Steps to Reproduce the Problem
- local components folder contains a pubsub.yaml file with following config:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.azure.servicebus
  metadata:
    - name: connectionString
      value: "Endpoint=sb://riot...-> from azure portal primary connection string"
```
Started first the normal java application (that has no subscription endpoints). Then the Dapr side car.  When I call then the exposed REST API from the java application an event should be published. 
Yesterday with the known topic this worked. Today I had to use a new topic, then the exception occurred.

**Comment by artursouza** [comment]
Hi @pagufler,

Since the SDK 0.3, Dapr client is communicating via Grpc and Http. Grpc is used for every API except actors. Actor APIs are over HTTP. When running your example, please make sure the env variable DAPR_GRPC_PORT is set to the same port that the Dapr sidecar is listening to.

Please, let me know if this helps.

**Comment by pagufler** [comment]
Hi @artursouza,

I tried what you suggested:
Java App started with following env variables regarding dapr:
DAPR_HTTP_PORT=3001;
DAPR_GRPC_PORT=5001

This is how I run the dapr sidecar
dapr run --app-id core --app-port 8081 --port 3001 --grpc-port 5001 -- cat

But still I get the error:
2020/03/25T22:02:47.400 core [http-nio-8081-exec-2] ERROR c.b.r.s.ServiceImpl.lambda$publishAdapterEvent$3(486) - io.grpc.StatusRuntimeException: UNAVAILABLE: io exception [161818, , Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36]
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at io.dapr.client.DaprClientGrpc.lambda$publishEvent$0(DaprClientGrpc.java:91)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4193)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4059)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3995)
	at com.bosch.riot.server.restapi.ServiceImpl.publishAdapterEvent(ServiceImpl.java:487)

**Comment by pagufler** [comment]
Hi @artursouza,

seams that yesterday my head was not really working...
Mistakenly took a connection string that was already taken by someone else. Then we get this error msg. 
Would be good to have a hint, that a connection string is used twice.

This bug can therefore be closed

**Comment by artursouza** [comment]
Here is one thing to identify if the problem is between Dapr SDK and Dapr runtime or between DaprRuntime and the component's endpoint:

=> Publish via dapr cli using instructions from https://github.com/dapr/samples/tree/master/4.pub-sub#use-the-cli-to-publish-messages-to-subscribers

If this works, it means the problem is in the SDK. If it does not work, the problem is between dapr sidecar and the PubSub component it is communicating with.

Also, can you share the logs from Dapr sidecar? If that is generic, we need to fix that first.

**Comment by javageek79** [comment]
hi, the error occured again this morning. Exception is still the same as reported.
To analyze, we've executed 
`[root@xxx/]# curl -X POST http://localhost:3500/v1.0/publish/core.adapters.delete -H "Content-Type: application/json"  -d '{
       "status": "completed"
     }'
[root@core-99fbbd855-qt66r /]# ` 
successfully in the container on our AKS
related logs are provided 
[here -> sidecar-log_30032020.txt](https://github.com/dapr/java-sdk/files/4402012/sidecar-log_30032020.txt)

**Comment by artursouza** [comment]
Hi @javageek79 ,

Java SDK uses GRPC to invoke all APIs, except Actor-related. In the application side, echo the value of DAPR_GRPC_PORT env variable. Then, confirm this value is the same that the sidecar container is printing out. If the ports are different, then that is the problem.

Next, let's confirm if the SDK can talk to the sidecar via HTTP. At the start up of your application, before creating a DaprClient instance, switch the SDK to HTTP mode via `System.getProperties().setProperty("dapr.grpc.enabled", "false");` If the problem persists, then there is a general connection issue between the app and the sidecar.

Just to clarify, we do have automated integration tests in the Java SDK to validate all features work with the sidecar. In these connectivity issues, we must understand the environment first.

**Comment by LMWF** [comment]
Is this error occurring after the app has been up a while or is it near the time it starts up?

**Comment by pagufler** [comment]
Hi,
we checked the env var DAPR_GRPC_PORT  in the application container and in the corresponding dapr side car. They are the same.

We disabled grpc when the application starts at the very beginning. **Then the event was successfully published and the consumers got the event.**
So it seams the problem lies with the GRPC.

We have now the disablement of grpc in place. let us know when the fix is available.

@LMWF  the error occured in our application when we wanted to publish an event (as this app is at the moment only a publisher, no subscriber and no actor).

**Comment by RicardoNiepel** [comment]
Please update to 0.6.0 because there were GRPC changes in it and let us know if the issue still exists.

**Comment by artursouza** [comment]
Can this issue be closed?

**Comment by artursouza** [comment]
Closing this issue. Please, open a new one if issue persists.

**Comment by jasparmang** [comment]
Hello,

we still have this issue for our java service and we also have it for the node js applications and the node js sdk.
But let us focus on the Java app. The code is still the same as mentioned above. Here are our dapr logs and our error:
[core_error.txt](https://github.com/dapr/java-sdk/files/4514698/core_error.txt)
[core_dapr.log](https://github.com/dapr/java-sdk/files/4514699/core_dapr.log)

**Comment by artursouza** [comment]
Error from app:
```
io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:50051\nCaused by: java.net.ConnectException: finishConnect(..) failed: Connection refused\n\tat 
```

Log entry from sidecar:
```
time="2020-04-22T06:44:09.271930095Z" level=info msg="API gRPC server is running on port 50001" app_id=core instance=core-6b86489796-tm98x scope=dapr.runtime type=log ver=0.6.0
```

Please, use environment variable DAPR_GRPC_PORT to set the correct port on app and use `--grpc-port` argument on `dapr.exe` to set the correct port on dev environment.

**Comment by javageek79** [comment]
> Error from app:
> 
> ```
> io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:50051\nCaused by: java.net.ConnectException: finishConnect(..) failed: Connection refused\n\tat 
> ```
> 
> Log entry from sidecar:
> 
> ```
> time="2020-04-22T06:44:09.271930095Z" level=info msg="API gRPC server is running on port 50001" app_id=core instance=core-6b86489796-tm98x scope=dapr.runtime type=log ver=0.6.0
> ```
> 
> Please, use environment variable DAPR_GRPC_PORT to set the correct port on app and use `--grpc-port` argument on `dapr.exe` to set the correct port on dev environment.

java-sdk is using `50051` as default [DAPR_GRPC_PORT in Properties.java](https://github.com/dapr/java-sdk/blob/818667ed2ef4427b228afe3d00a7481d876b55ed/sdk/src/main/java/io/dapr/utils/Properties.java#L26) is that correct? We think, that had caused the latest reported issue

**Comment by yaron2** [comment]
> > Error from app:
> > ```
> > io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:50051\nCaused by: java.net.ConnectException: finishConnect(..) failed: Connection refused\n\tat 
> > ```
> > 
> > 
> > Log entry from sidecar:
> > ```
> > time="2020-04-22T06:44:09.271930095Z" level=info msg="API gRPC server is running on port 50001" app_id=core instance=core-6b86489796-tm98x scope=dapr.runtime type=log ver=0.6.0
> > ```
> > 
> > 
> > Please, use environment variable DAPR_GRPC_PORT to set the correct port on app and use `--grpc-port` argument on `dapr.exe` to set the correct port on dev environment.
> 
> java-sdk is using `50051` as default [DAPR_GRPC_PORT in Properties.java](https://github.com/dapr/java-sdk/blob/818667ed2ef4427b228afe3d00a7481d876b55ed/sdk/src/main/java/io/dapr/utils/Properties.java#L26) is that correct? We think, that had caused the latest reported issue

Needs to be 50001

**Comment by artursouza** [comment]
That explains it. We are fixing that today.
